config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "submissions#index"

  namespace :inbox do
    resources :thread_reply_notifications, only: [:index, :update]
  end
  get "inbox", to: "inbox/thread_reply_notifications#index"

  resources :submissions, only: [:index, :new, :create]
  get "/submissions/:submission_action", to: "submissions#index", as: :marked_submissions
  resources :submissions, only: [:show], param: :short_id, path: :s do
    resources :comments, only: [:create]
  end

  resources :tags, only: [], path: :t do
    resources :submissions, only: [:index]
  end

  get "/pages/:page", to: "pages#show", as: :pages

  get "u/:username/submissions", to: "submissions#index", as: :user_submissions
  get "/u/:username/comments", to: "user_comments#index", as: :user_comments

  namespace :users do
    resource :submission_actions, only: [:update]
  end

  resources :user_invitations, only: [:create]

  namespace :admin do
    resources :comment_removals, only: [:index, :show, :new, :create, :destroy]
    resources :submission_removals, only: [:index, :show, :new, :create, :destroy]
    resources :tags, only: [:index, :new, :edit, :create, :update]
    resources :users, only: [:index, :show, :edit, :update]
  end

  post "/admin/users/:id/unban", to: "admin/users#unban", as: :admin_unban_user

  namespace :api do
    namespace :v1 do
      resources :comments, only: [], param: :short_id do
        put :upvotes, action: :update, controller: "comments/upvotes"
        put :downvotes, action: :update, controller: "comments/downvotes"
      end

      resources :submissions, only: [], param: :short_id do
        put :upvotes, action: :update, controller: "submissions/upvotes"
        put :downvotes, action: :update, controller: "submissions/downvotes"
      end
    end
  end
end

app/models/submission_removal.rb
class SubmissionRemoval < ApplicationRecord
  belongs_to :submission
  belongs_to :removed_by, class_name: :User

  enum reason: {
    off_topic: 0,
    spam: 1,
    doxxing: 666
  }
end

app/controllers/admin/submission_removals_controller.rb
module Admin
  class SubmissionRemovalsController < BaseController
    DEFAULT_PAGE = 0
    DEFAULT_PER_PAGE = 25

    def index
      @paginator = ResultsPaginator.new(
        authorized_scope(SubmissionRemoval.includes(:removed_by, submission: :user)),
        pagination_params
      )
    end

    def show
      @removal = SubmissionRemoval.includes(:removed_by, submission: :user).find(params[:id])
      authorize! @removal, to: :show?
    end

    def new
      @submission = Submission.includes(:user).friendly.
        find(submission_removal_params.delete(:submission_short_id))
      @removal = SubmissionRemoval.new(submission_removal_params.merge(submission_id: @submission.id))
    end

    def create
      Submission.friendly.find(submission_removal_params.delete(:submission_short_id)).then do |s|
        s.update!(removed: true)
        SubmissionRemoval.where(submission: s).
          first_or_create!(submission_removal_params.merge(removed_by: current_user))
      end

      redirect_to admin_submission_removals_path, notice: t(".success")
    end

    def destroy
      removal = SubmissionRemoval.includes(:submission).find(params[:id])
      removal.submission.update!(removed: false)
      removal.destroy!

      redirect_to admin_submission_removals_path, notice: t(".success")
    end

    private

    def pagination_params
      {
        page: params.fetch(:page, DEFAULT_PAGE),
        per_page: params.fetch(:per_page, DEFAULT_PER_PAGE),
        order: { created_at: :desc }
      }
    end

    def submission_removal_params
      @_submission_removal_params ||= params.
        require(:submission_removal).
        permit(:submission_short_id, :reason, :details)
    end
  end
end

app/views/admin/submission_removals/index.html.haml
%h1= t(".title")

%table.removal-table
  %thead
    %tr
      %td= t(".submission_title")
      %td= t(".submission_author")
      %td= t(".removed_by")
      %td= t(".reason")
      %td= t(".details")
      %td
  %tbody
    - @paginator.results_page.each do |removal|
      %tr{ id: "removal_#{removal.id}" }
        %td
          = link_to removal.submission.title, submission_path(removal.submission.short_id)
        %td
          = link_to removal.submission.user.username,
            user_submissions_path(removal.submission.user.username)
        %td= removal.removed_by.username
        %td= removal.reason
        %td= truncate(removal.details)
        %td
          = link_to t(".view"), admin_submission_removal_path(removal)
          = link_to t(".undo"), admin_submission_removal_path(removal),
            data: { confirm: t(".confirm_reverse_removal") },
            method: :delete
= render "shared/pagination_controls",
  paginator: @paginator,
  path_helper: ->(params) { admin_submission_removals_path(params) }

app/views/admin/submission_removals/new.html.haml
%h1= t(".remove_submission")
.removal-container
  .removable
    %div
      = t(".submission_title")
      %span
        = link_to @submission.title, submission_path(@submission.short_id)
    %div
      = t(".submission_author")
      %span
        = link_to @submission.user.username, user_submissions_path(@submission.user.username)

  = simple_form_for [:admin, @removal] do |f|
    = f.input :reason, collection: SubmissionRemoval.reasons.keys
    = f.input :details
    = f.input :submission_short_id, as: :hidden, input_html: { value: @submission.short_id }, wrapper: false
    = f.button :submit, t(".submit")

app/views/admin/submission_removals/show.html.haml
%h1.breadcrumb
  = link_to t("admin.submission_removals.index.title"), admin_submission_removals_path
  = "/ #{t('.title')}"

.removal-container
  .removal-info
    %div
      %label= t(".submission_title")
      %span
        = link_to @removal.submission.title, submission_path(@removal.submission.short_id)
    %div
      %label= t(".submission_author")
      %span
        = link_to @removal.submission.user.username, user_submissions_path(@removal.submission.user.username)
    %div
      %label= t(".removed_by")
      %span= @removal.removed_by.username
    %div
      %label= t(".reason")
      %span= @removal.reason
    %div
      %label= t(".details")
      %span= @removal.details