config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "submissions#index"

  namespace :inbox do
    resources :thread_reply_notifications, only: [:index, :update]
  end
  get "inbox", to: "inbox/thread_reply_notifications#index"

  resources :submissions, only: [:index, :new, :create]
  get "/submissions/:submission_action", to: "submissions#index", as: :marked_submissions
  resources :submissions, only: [:show], param: :short_id, path: :s do
    resources :comments, only: [:create]
  end

  resources :tags, only: [], path: :t do
    resources :submissions, only: [:index]
  end

  get "/pages/:page", to: "pages#show", as: :pages

  get "u/:username/submissions", to: "submissions#index", as: :user_submissions
  get "/u/:username/comments", to: "user_comments#index", as: :user_comments

  namespace :users do
    resource :submission_actions, only: [:update]
  end

  resources :user_invitations, only: [:create]

  namespace :admin do
    resources :comment_removals, only: [:index, :show, :new, :create, :destroy]
    resources :submission_removals, only: [:index, :show, :new, :create, :destroy]
    resources :tags, only: [:index, :new, :edit, :create, :update]
    resources :users, only: [:index, :show, :edit, :update]
  end

  post "/admin/users/:id/unban", to: "admin/users#unban", as: :admin_unban_user

  namespace :api do
    namespace :v1 do
      resources :comments, only: [], param: :short_id do
        put :upvotes, action: :update, controller: "comments/upvotes"
        put :downvotes, action: :update, controller: "comments/downvotes"
      end

      resources :submissions, only: [], param: :short_id do
        put :upvotes, action: :update, controller: "submissions/upvotes"
        put :downvotes, action: :update, controller: "submissions/downvotes"
      end
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  ID_REGEX = /\A[a-z]+(-[a-z0-9]+|[a-z0-9])*\z/
  enum kind: {
    topic: 0,
    media: 5,
    source: 10,
    meta: 15,
    mod: 20
  }

  validate :validate_tag_id_format

  has_many :submission_tags
  has_many :submissions, through: :submission_tags

  def self.for_user(user)
    if user.moderator? || user.admin?
      Tag.all
    else
      Tag.where.not(kind: :mod)
    end
  end

  private

  def validate_tag_id_format
    unless id.match?(ID_REGEX)
      errors.add(:id, "ID must match format: #{ID_REGEX.inspect}")
    end
  end
end

app/controllers/admin/tags_controller.rb
module Admin
  class TagsController < BaseController
    def index
      @grouped_tags = Tag.order(:description).to_a.group_by(&:kind)
    end

    def new
      @tag = Tag.new(kind: params[:kind])
    end

    def edit
      @tag = Tag.find(params[:id])
    end

    def create
      @tag = Tag.create(create_tag_params)
      if @tag.errors.none?
        redirect_to admin_tags_path, notice: t(".success")
      else
        render :new
      end
    end

    def update
      @tag = Tag.find(params[:id])
      if @tag.update(update_tag_params)
        redirect_to admin_tags_path, notice: t(".success")
      else
        render :edit
      end
    end

    private

    def create_tag_params
      params.require(:tag).permit(:id, :kind, :description)
    end

    def update_tag_params
      params.require(:tag).permit(:kind, :description)
    end
  end
end

app/views/admin/tags/_form.html.haml
= simple_form_for [:admin, tag] do |f|
  = f.input :id, disabled: tag.persisted?
  = f.input :kind, collection: Tag.kinds.keys, include_blank: false
  = f.input :description
  = f.button :submit

app/views/admin/tags/edit.html.haml
%h1.breadcrumb
  = link_to t("admin.tags.index.title"), admin_tags_path
  = "/ #{t('.title')}"
.tag-form
  = render "form", tag: @tag

app/views/admin/tags/index.html.haml
%h1= t(".title")
- Tag.kinds.each_key do |tag_kind|
  .tag-table{ class: "#{tag_kind}-tag-table" }
    %h2.tag-table-header= t(".#{tag_kind}")
    = link_to t(".new_#{tag_kind}_tag"), new_admin_tag_path(kind: tag_kind), class: "new-tag"
    %table
      %thead
        %tr
          %td= t(".id")
          %td= t(".description")
          %td= t(".actions")
      %tbody
        - if @grouped_tags[tag_kind].present?
          - @grouped_tags[tag_kind].each do |tag|
            %tr
              %td= render "shared/tag", tag: tag
              %td= tag.description
              %td= link_to t(".edit"), edit_admin_tag_path(tag.id)
    - if @grouped_tags[tag_kind].blank?
      .no-tags= t(".no_tags")

app/views/admin/tags/new.html.haml
%h1.breadcrumb
  = link_to t("admin.tags.index.title"), admin_tags_path
  = "/ #{t('.title')}"
.tag-form
  = render "form", tag: @tag